In [1]:
#all dependices

import pandas as pd
import numpy as np
import re
import os
from pathlib import Path

In [70]:
#import the datafile

df = pd.read_csv("/home/navneet/Documents/preprocessing/test.csv")
df.head()

,G_ID,PART_ID,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,ADDRESS_LINE4,ADDRESS_LINE,POSTCODE
0,1864732,2365061,NaN,RAJ PUA,HIRANAGAR,KATHUA,JAMMU AND KASHMIR,184145.0
1,1864911,78345783,WARD NO 58,DIGIANA CAMP~DIGIANA,NEAR SANT MELA SINGH COLLEGE OF EDUCATIONS,JAMMU,JAMMU AND KASHMIR,180010.0
2,1864969,78447671,WARD NO 2~NEAR GHS BANHORE,BILLAWAR~BILLAWAR,DANBRAH,KATHUA,JAMMU AND KASHMIR,184203.0
3,1865060,5333622,GOVINDPURI VIJAYPUR,VIJAYPUR~,. SAMBA,JAMMU,JAMMU AND KASHMIR,184120.0
4,1865344,8588662,NaN,"ARNIA , ~BISHNAH",CHAK GORIYAN,JAMMU,JAMMU AND KASHMIR,181131.0

In [80]:
#step 6 pincode length and remove any alphabet from pincode column
df['POSTCODE'] = df['POSTCODE'].astype(str).str.extract('(\d{6})', expand=False)
df.head()

,G_ID,PART_ID,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,ADDRESS_LINE4,ADDRESS_LINE,POSTCODE
0,1864732,2365061,NaN,RAJ PUA,HIRANAGAR,KATHUA,JAMMU AND KASHMIR,184145
1,1864911,78345783,WARD NO 58,DIGIANA CAMP~DIGIANA,NEAR SANT MELA SINGH COLLEGE OF EDUCATIONS,JAMMU,JAMMU AND KASHMIR,180010
2,1864969,78447671,WARD NO 2~NEAR GHS BANHORE,BILLAWAR~BILLAWAR,DANBRAH,KATHUA,JAMMU AND KASHMIR,184203
3,1865060,5333622,GOVINDPURI VIJAYPUR,VIJAYPUR~,. SAMBA,JAMMU,JAMMU AND KASHMIR,184120
4,1865344,8588662,NaN,"ARNIA , ~BISHNAH",CHAK GORIYAN,JAMMU,JAMMU AND KASHMIR,181131

In [85]:
#Step 1 - Filtering out of Keywords 
#find village and post keyword and replace it by space

for col in df:
    df[col]= df[col].replace('village', " ")
    df[col]= df[col].replace('post', " ")
df.head(20)

,G_ID,PART_ID,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,ADDRESS_LINE4,ADDRESS_LINE,POSTCODE
0,1864732,2365061,NaN,RAJ PUA,HIRANAGAR,KATHUA,JAMMU AND KASHMIR,184145
1,1864911,78345783,WARD NO 58,DIGIANA CAMP~DIGIANA,NEAR SANT MELA SINGH COLLEGE OF EDUCATIONS,JAMMU,JAMMU AND KASHMIR,180010
2,1864969,78447671,WARD NO 2~NEAR GHS BANHORE,BILLAWAR~BILLAWAR,DANBRAH,KATHUA,JAMMU AND KASHMIR,184203
3,1865060,5333622,GOVINDPURI VIJAYPUR,VIJAYPUR~,. SAMBA,JAMMU,JAMMU AND KASHMIR,184120
4,1865344,8588662,NaN,"ARNIA , ~BISHNAH",CHAK GORIYAN,JAMMU,JAMMU AND KASHMIR,181131
5,1865381,48427963,ACHABAL,MASJID SHAREEF AAHU PAISAN~ACHABAL,ANANTNAG,ANANTNAG,JAMMU AND KASHMIR,192201
6,1865429,79632406,NaN,V P O JAKHBAR NR GOVT HGR SEC JAKHBAR KATHUA~...,KATHUA,KATHUA,JAMMU AND KASHMIR,184104
7,1865547,82101982,066~NEAR GOVT HIGHER SECONDARY SCHOOL,KANKAR NALLAH NAHARLAGUN~MODEL,PAPUM PARE,PAPUM PARE,ARUNACHAL PRADESH,791110
8,1865656,78446840,DINGA AMB~,~DINGA AMB,DINGA AMB,KATHUA,JAMMU AND KASHMIR,184144
9,1865696,79367796,NaN,FATWAL~BISHNAH ADDA,JAMMU,JAMMU,JAMMU AND KASHMIR,181132
10,1865855,26183077,NaN,NARSING GARD~,BALGARDEN,SRINAGAR,JAMMU AND KASHMIR,190010
11,1866092,57620672,NaN,SERICULTURE NUSSERY~ANDERGAM,JAMMU AND KASHMIR,BARAMULLA,JAMMU AND KASHMIR,193121
12,1866227,5116209,NaN,H. NO. 98-B MOHALLA DALPATIAN,JAMMU,JAMMU,JAMMU AND KASHMIR,180001
13,1866338,4324393,NaN,LADOORA MOHALLA BHRA,RAFIABAD,BARAMULA,JAMMU AND KASHMIR,193101
14,1866345,80978045,NaN,CHECK KANISRA~BARAMULLA,MASJID SHAREEF,BARAMULLA,JAMMU AND KASHMIR,193101
15,1866550,78448897,WARD NO-65-165,NEAR DHARMAL TEMPLE~JAMMU,BARNAI,JAMMU,JAMMU AND KASHMIR,181205
16,1866869,64713587,MAIRA,JOURIAN~,AKHNOOR,JAMMU,JAMMU AND KASHMIR,181202
17,1867057,81986408,~PATOLI,PATOLI BRAHMANA~MUTHI,BRAHAMANA DHAMWAL,JAMMU,JAMMU AND KASHMIR,181205
18,1867103,79887310,~ DEBRAH,KRIMACHI NEAR GOVT SCHOOL DEBRAH~UDHAMPUR,UDHAMPUR,UDHAMPUR,JAMMU AND KASHMIR,182101
19,1867148,81904340,PANIHAD NEAR HR SEC SCHOOL,PANIHAD~PANIHAD,RAJOURI,RAJOURI,JAMMU AND KASHMIR,185132

In [84]:
#step 5 to remove special char from the database

import re
lis=[]
pattern = r'[^A-Za-z0-9 ]'
regex = re.compile(pattern)

for col in df:
    s=df[col].tolist()
    for i in s:
        lis.append(str(regex.sub('', str(i))))
r=pd.DataFrame(lis)

            0
0     1864732
1     1864911
2     1864969
3     1865060
4     1865344
...       ...
1647  2038497
1648  2038526
1649  2038539
1650  2038711
1651  2038804

[1652 rows x 1 columns]

,G_ID,PART_ID,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,ADDRESS_LINE4,ADDRESS_LINE,POSTCODE
0,1864732,2365061,NaN,RAJ PUA,HIRANAGAR,KATHUA,JAMMU AND KASHMIR,184145
1,1864911,78345783,WARD NO 58,DIGIANA CAMPDIGIANA,NEAR SANT MELA SINGH COLLEGE OF EDUCATIONS,JAMMU,JAMMU AND KASHMIR,180010
2,1864969,78447671,WARD NO 2NEAR GHS BANHORE,BILLAWARBILLAWAR,DANBRAH,KATHUA,JAMMU AND KASHMIR,184203
3,1865060,5333622,GOVINDPURI VIJAYPUR,VIJAYPUR,SAMBA,JAMMU,JAMMU AND KASHMIR,184120
4,1865344,8588662,NaN,"ARNIA , BISHNAH",CHAK GORIYAN,JAMMU,JAMMU AND KASHMIR,181131
5,1865381,48427963,ACHABAL,MASJID SHAREEF AAHU PAISANACHABAL,ANANTNAG,ANANTNAG,JAMMU AND KASHMIR,192201
6,1865429,79632406,NaN,V P O JAKHBAR NR GOVT HGR SEC JAKHBAR KATHUAJ...,KATHUA,KATHUA,JAMMU AND KASHMIR,184104
7,1865547,82101982,066NEAR GOVT HIGHER SECONDARY SCHOOL,KANKAR NALLAH NAHARLAGUNMODEL,PAPUM PARE,PAPUM PARE,ARUNACHAL PRADESH,791110
8,1865656,78446840,DINGA AMB,DINGA AMB,DINGA AMB,KATHUA,JAMMU AND KASHMIR,184144
9,1865696,79367796,NaN,FATWALBISHNAH ADDA,JAMMU,JAMMU,JAMMU AND KASHMIR,181132
10,1865855,26183077,NaN,NARSING GARD,BALGARDEN,SRINAGAR,JAMMU AND KASHMIR,190010
11,1866092,57620672,NaN,SERICULTURE NUSSERYANDERGAM,JAMMU AND KASHMIR,BARAMULLA,JAMMU AND KASHMIR,193121
12,1866227,5116209,NaN,H NO 98-B MOHALLA DALPATIAN,JAMMU,JAMMU,JAMMU AND KASHMIR,180001
13,1866338,4324393,NaN,LADOORA MOHALLA BHRA,RAFIABAD,BARAMULA,JAMMU AND KASHMIR,193101
14,1866345,80978045,NaN,CHECK KANISRABARAMULLA,MASJID SHAREEF,BARAMULLA,JAMMU AND KASHMIR,193101
15,1866550,78448897,WARD NO-65-165,NEAR DHARMAL TEMPLEJAMMU,BARNAI,JAMMU,JAMMU AND KASHMIR,181205
16,1866869,64713587,MAIRA,JOURIAN,AKHNOOR,JAMMU,JAMMU AND KASHMIR,181202
17,1867057,81986408,PATOLI,PATOLI BRAHMANAMUTHI,BRAHAMANA DHAMWAL,JAMMU,JAMMU AND KASHMIR,181205
18,1867103,79887310,DEBRAH,KRIMACHI NEAR GOVT SCHOOL DEBRAHUDHAMPUR,UDHAMPUR,UDHAMPUR,JAMMU AND KASHMIR,182101
19,1867148,81904340,PANIHAD NEAR HR SEC SCHOOL,PANIHADPANIHAD,RAJOURI,RAJOURI,JAMMU AND KASHMIR,185132

In [33]:
import re
lis=[]
pattern = r'[^A-Za-z0-9 ]'
regex = re.compile(pattern)
s=df['ADDRESS_LINE1'].tolist()
length = len(s) 
for i in s:
    lis.append(str(regex.sub('', str(i))))
ser=pd.Series(lis)
ser

0                                                     nan
1                                              WARD NO 58
2                               WARD NO 2NEAR GHS BANHORE
3                                     GOVINDPURI VIJAYPUR
4                                                     nan
                              ...
6016                              3 NILAY BARSE SHIV WADI
6017                                            57 LABDHI
6018    Krishna Nagar Colony Phase 2nd Quarali bye pas...
6019                             RANGOLI  E  BLOCK MARKET
6020                             FLAT NO 008 EGK ENCLAVVE
Length: 6021, dtype: object

In [50]:
df.columns

Index(['G_ID', 'PART_ID', 'ADDRESS_LINE1', 'ADDRESS_LINE2', 'ADDRESS_LINE3',
       'ADDRESS_LINE4', 'ADDRESS_LINE', 'POSTCODE'],
      dtype='object')

In [54]:
for col in df:
    s=df[col]
    print(s)

0       1864732
1       1864911
2       1864969
3       1865060
4       1865344
         ...
6016    2273282
6017    2274918
6018    2282037
6019    2292135
6020    2294762
Name: G_ID, Length: 6021, dtype: object
0        2365061
1       78345783
2       78447671
3        5333622
4        8588662
          ...
6016     1323805
6017    76120920
6018    72992968
6019     4750200
6020     4798999
Name: PART_ID, Length: 6021, dtype: object
0                                                     NaN
1                                              WARD NO 58
2                               WARD NO 2NEAR GHS BANHORE
3                                     GOVINDPURI VIJAYPUR
4                                                     NaN
                              ...
6016                            3 "NILAY" BARSE SHIV WADI
6017                                         5/7 "LABDHI"
6018    Krishna Nagar Colony Phase 2nd Quarali bye pas...
6019                           RANGOLI " E " BLOCK MARKET
6020                            FLAT NO: 008 EGK ENCLAVVE
Name: ADDRESS_LINE1, Length: 6021, dtype: object
0                                        RAJ PUA
1                            DIGIANA CAMPDIGIANA
2                               BILLAWARBILLAWAR
3                                       VIJAYPUR
4                                ARNIA , BISHNAH
                          ...
6016                           KALANALABHAVNAGAR
6017                                      GODHRA
6018     CHAMPA VIHARALIGARH BEGAM BAGH ALIGARH"
6019                                     COMPLEX
6020                       BESIDE BAWARCHI HOTEL
Name: ADDRESS_LINE2, Length: 6021, dtype: object
0                                        HIRANAGAR
1       NEAR SANT MELA SINGH COLLEGE OF EDUCATIONS
2                                          DANBRAH
3                                            SAMBA
4                                     CHAK GORIYAN
                           ...
6016                     OPP DADASAHEB JAIN TEMPLE
6017                          MAHAVIR JAIN SOCIETY
6018                                    BEGAM BAGH
6019                                       DHANBAD
6020                                  RTC "X ROADS
Name: ADDRESS_LINE3, Length: 6021, dtype: object
0                    KATHUA
1                     JAMMU
2                    KATHUA
3                     JAMMU
4                     JAMMU
               ...
6016              BHAVNAGAR
6017    PANCHMAHAL (GODHRA)
6018                ALIGARH
6019                DHANBAD
6020              HYDERABAD
Name: ADDRESS_LINE4, Length: 6021, dtype: object
0       JAMMU AND KASHMIR
1       JAMMU AND KASHMIR
2       JAMMU AND KASHMIR
3       JAMMU AND KASHMIR
4       JAMMU AND KASHMIR
              ...
6016              GUJARAT
6017              GUJARAT
6018        UTTAR PRADESH
6019            JHRAKHAND
6020            TELANGANA
Name: ADDRESS_LINE, Length: 6021, dtype: object
0       184145
1       180010
2       184203
3       184120
4       181131
         ...
6016    364001
6017    389001
6018    202001
6019    110003
6020    500020
Name: POSTCODE, Length: 6021, dtype: object